[package]
name = "zeropool-tx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
fawkes-crypto = "4.4.0"
serde = "1.0.163"

[features]
default = ["std"]
std = ["serde/std"]